- name: Deploy web app to EC2 instance
  hosts: "existing-server"
  gather_facts: yes
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Create application directory
      file:
        path: /opt/springboot
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Deploy application files
      copy:
        src: /var/jenkins_home/workspace/pring-petclinic-multibranch_main/target/spring-petclinic-3.4.0-SNAPSHOT.jar
        dest: /opt/springboot/spring-petclinic.jar
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Create startup script
      copy:
        dest: /opt/springboot/start-app.sh
        content: |
          #!/bin/bash
          nohup java -jar /opt/springboot/spring-petclinic.jar > /opt/springboot/app.log 2>&1 &
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Run application
      become: yes
      become_user: ec2-user
      shell: /opt/springboot/start-app.sh
